# -*- coding: utf-8 -*-
"""Untitled36.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W576yI-xWshc7Joqe2rxwD9k_1Q3hp28
"""

!pip install ultralytics roboflow opencv-python supervision mediapipe

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="uJP84hZ5uT5TaW44DMUV")
project = rf.workspace("chathu-6c46u").project("nn-ihnoe")
version = project.version(1)
dataset = version.download("yolov8")

import os
os.listdir("/content/nn-1")

os.listdir("/content/nn-1")
os.listdir("/content/nn-1/train")

with open("/content/nn-1/data.yaml", "r") as f:
    print(f.read())

import os
print(os.listdir("/content/nn-1"))

print(os.listdir("/content/nn-1/train"))

import os, shutil, random

train_img_dir = "/content/nn-1/train/images"
train_lbl_dir = "/content/nn-1/train/labels"

valid_img_dir = "/content/nn-1/valid/images"
valid_lbl_dir = "/content/nn-1/valid/labels"

os.makedirs(valid_img_dir, exist_ok=True)
os.makedirs(valid_lbl_dir, exist_ok=True)

images = os.listdir(train_img_dir)
random.shuffle(images)

# take 20% for validation
val_count = int(0.2 * len(images))
val_images = images[:val_count]

for img in val_images:
    shutil.move(os.path.join(train_img_dir, img), os.path.join(valid_img_dir, img))

    label = img.replace(".jpg", ".txt").replace(".png", ".txt")
    shutil.move(os.path.join(train_lbl_dir, label), os.path.join(valid_lbl_dir, label))

print("Validation set created:", len(val_images))

from ultralytics import YOLO

model = YOLO("yolov8n.pt")

model.train(
    data="/content/nn-1/data.yaml",
    epochs=50,
    imgsz=640,
    batch=8
)

from ultralytics import YOLO

model = YOLO("/content/runs/detect/train2/weights/best.pt")

metrics = model.val(data="/content/nn-1/data.yaml")

print("Precision:", metrics.results_dict["metrics/precision(B)"])
print("Recall:", metrics.results_dict["metrics/recall(B)"])
print("mAP50 (Accuracy):", metrics.results_dict["metrics/mAP50(B)"])
print("mAP50-95:", metrics.results_dict["metrics/mAP50-95(B)"])

!pip install ultralytics opencv-python supervision mediapipe

!pip install roboflow

from roboflow import Roboflow

!pip install roboflow

from roboflow import Roboflow

rf = Roboflow(api_key="uJP84hZ5uT5TaW44DMUV")
project = rf.workspace("chathu-6c46u").project("nn-ihnoe")
version = project.version(1)
dataset = version.download("yolov8")

import os
print(os.listdir("/content"))

import os
print(os.listdir("/content/nn-1"))

with open("/content/nn-1/data.yaml","r") as f:
    print(f.read())

train: /content/nn-1/train/images
val: /content/nn-1/val/images